# Generated by Django 4.0.5 on 2022-06-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_announcement_name_alter_event_name_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='category',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
