# Generated by Django 4.0.5 on 2022-06-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_neighbourhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
