# Generated by Django 4.0.5 on 2022-06-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_alert_category_remove_announcement_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
