# Generated by Django 4.0.5 on 2022-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default='testing', max_length=120),
            preserve_default=False,
        ),
    ]
