# Generated by Django 4.0.5 on 2022-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='fire_dept_contact',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_dept_contact',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_dept_contact',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
