# Generated by Django 4.0.5 on 2022-06-19 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_neighbourhood_fire_dept_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='fire_dept_contact',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='health_dept_contact',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='number_of_occupants',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_dept_contact',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
