# Generated by Django 4.0.5 on 2022-06-19 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_neighbourhood_fire_dept_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_contact',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
