# Generated by Django 4.0.5 on 2022-06-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_business_business_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood_posts', to='main.neighbourhood'),
        ),
    ]
